### ISSUE TITLE
Update the Institute registration form.

### ISSUE THREAD

**Issue by dotslash21** [dotslash21/tpo-reg-page#2]
An associate from Central Placement Committee , West Bengal contacted me about some changes in the website's University/Institute Registration form with the fields given below. As you know, this project is nearing final phase, any significant changes can(will) break the functionality of the site. So keeping this fact in mind I've informed him of the technical aspects and negotiated with the associate about the changes. He has given us the freedom to decide on which changes to ignore should they break the critical functionality of the site. So we need to implement those number of changes as much as possible without jeopardizing the website's functionality.

<hr>

INSTITUTE REGISTRATION FORM

1. University / Institute Name
2. Website
3. Approval and Affiliation
4. Accreditation (if any)
5. Year Of Establishment
6. Institute Type (Govt. /Govt. Aided / Pvt. /Self Finance)
7. Address 
8. Contact No. 
9. Head of the Institute
10. Course 
11. College / Stream wise Strength of Current Batch
12.Placement in Charge
13.Mobile No.
14.Email ID
15.Infrastructure support for placement

I) No. of Systems with LAN connection 
II)Internet Speed
III)Seminar Hall Capacity
IV)Misc.

**Comment by bagofcodes** [comment]
Update ki korte hobe?

**Comment by dotslash21** [comment]
The change request has been cancelled by the Associate himself.
